// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_nrCUj25l0gk4c87WWRhNoHTOqm6n9ug',
    appId: '1:587633322654:web:18e7b8a7af287bd235298f',
    messagingSenderId: '587633322654',
    projectId: 'adv-gen',
    authDomain: 'adv-gen.firebaseapp.com',
    storageBucket: 'adv-gen.appspot.com',
    measurementId: 'G-WCR7EYZ0E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPJrWfgYPXQLUZnEtriQ6vfT-Wfmwt4Hs',
    appId: '1:587633322654:android:e4c2ccc212e519f035298f',
    messagingSenderId: '587633322654',
    projectId: 'adv-gen',
    storageBucket: 'adv-gen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxGEVujWNNkLK2KfefgUTJza1wW02St0g',
    appId: '1:587633322654:ios:4ce208c592eff31435298f',
    messagingSenderId: '587633322654',
    projectId: 'adv-gen',
    storageBucket: 'adv-gen.appspot.com',
    iosClientId: '587633322654-bb683cregqvhdlikhpmj0c57tak6ful7.apps.googleusercontent.com',
    iosBundleId: 'com.example.addApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxGEVujWNNkLK2KfefgUTJza1wW02St0g',
    appId: '1:587633322654:ios:4ce208c592eff31435298f',
    messagingSenderId: '587633322654',
    projectId: 'adv-gen',
    storageBucket: 'adv-gen.appspot.com',
    iosClientId: '587633322654-bb683cregqvhdlikhpmj0c57tak6ful7.apps.googleusercontent.com',
    iosBundleId: 'com.example.addApp',
  );
}
